CREATE TABLE my_books (
                            id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                            name VARCHAR(255),
                            author VARCHAR(255),
                            price int
);
