CREATE TABLE my_books (
                          id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                          current_user_id INT, -- Новый столбец для хранения идентификатора пользователя
                          name VARCHAR(255),
                          author VARCHAR(255),
                          price INT,
                          quantity INT,
                          FOREIGN KEY (current_user_id) REFERENCES person(id) -- Внешний ключ, связывающий user_id с идентификатором пользователя в таблице person
);
